### ISSUE TITLE
[JBP-505] Send transaction thread describing relevant proposals

### ISSUE THREAD

**Issue by twodam** [nance-eth/nance-ts#104]
- [x] update backend to compile current governance cycle transactions (currently in a script state, needs to be functionized)
- [x] update backend to send reconfiguration to Tenderly for simulation (currently in broken state)
- [x] write backend tests for Tenderly transaction sending
- [x] update backend transaction message to show all relevant proposals
- [x] update backend transaction message to show the difference in funding distribution limit

**Comment by jigglyjams** [comment]
https://discord.com/channels/775859454780244028/1269009970264019014

![Image](https://github.com/user-attachments/assets/bb95fa14-cb92-4189-830a-3a30e3deaf43)
