### ISSUE TITLE
[JBP-505] Action to cancel a previous proposal

### ISSUE THREAD

**Issue by twodam** [nance-eth/nance-ts#105]
- [x] Create a new table that tracks active actions
- [x] Create active action API endpoint
- [x] Search active actions on frontend and allow for a user to select an action they want to cancel
- [x] On passing, remove the selected action from the active actions table

**Comment by jigglyjams** [comment]
https://github.com/nance-eth/nance-ts/commit/e3f2d013fc8339f1ece683f575e91e730f882335
