### ISSUE TITLE
actions endpoint

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-ts#111]
`/:space/actions` --> get all viable actions (everything that isnt "Cancelled", "Executed", or "Queued")

`/:space/actions/:uuid/poll` --> create poll for `pollRequired` action

**Comment by twodam** [comment]
1. `actions?status=Active` to return actions satisfied status filter, this is useful when creating Cancel action

1. `actions/71f7a6c628a34eb1b9ec35c7bc46822f` to return single action that has same uuid, this is useful when rendering Cancel action on proposal page

**Comment by jigglyjams** [comment]
https://api.nance.app/docs/#/default/spaceSpec_get_%2F%7Bspace%7D%2Factions%2F%7Baid%7D
